# Generated by Django 3.1.3 on 2020-11-27 19:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kanji', models.CharField(max_length=200)),
                ('kana', models.CharField(max_length=200)),
                ('meaning', models.TextField()),
                ('category', models.ManyToManyField(to='api.Category')),
            ],
        ),
    ]
