# Generated by Django 3.1.3 on 2020-12-06 06:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='PracticeHistory',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kanji', models.CharField(blank=True, max_length=200)),
                ('kana', models.CharField(max_length=200)),
                ('meaning', models.TextField()),
                ('category', models.ManyToManyField(to='api.Category')),
            ],
        ),
        migrations.CreateModel(
            name='WordNote',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('is_published', models.BooleanField(default=False)),
                ('associated_categories', models.ManyToManyField(to='api.Category')),
                ('associated_words', models.ManyToManyField(to='api.Word')),
            ],
        ),
        migrations.CreateModel(
            name='WordList',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('language', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('words', models.ManyToManyField(to='api.Word')),
            ],
        ),
    ]
