# Generated by Django 3.1.3 on 2020-12-06 09:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='practicehistory',
            name='data',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='practicehistory',
            name='last_update_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='practicehistory',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='practicehistory',
            name='version',
            field=models.FloatField(default=0),
        ),
    ]
