# Generated by Django 3.1.3 on 2020-11-27 21:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WordNote',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('associated_categories', models.ManyToManyField(to='api.Category')),
                ('associated_words', models.ManyToManyField(to='api.Word')),
            ],
        ),
        migrations.CreateModel(
            name='WordList',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('language', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('words', models.ManyToManyField(to='api.Word')),
            ],
        ),
    ]
