# Generated by Django 3.1.3 on 2020-11-28 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_wordlist_wordnote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='kanji',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
