# Generated by Django 3.1.3 on 2020-11-28 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20201129_0440'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordnote',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
