# Generated by Django 3.1.3 on 2020-11-30 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_wordnote_is_published'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wordnote',
            name='content',
        ),
    ]
